Add solutions to map problems
activeprofi/eu-python-learn-challenge pull request #2
Opened 2024-02-29 22:18 UTC by activeprofi

2024-03-04 05:19 UTC, aleksandr-semenov-dbp requested changes

2024-03-04 05:19 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +        filtered_movies = filter(lambda m: len(m["country"].split(",")) >= 2, list_of_movies)
это конечно мелочь, но использовать len(split()) для подсчета запятых очень неэффективно, split() создает новые строки, что довольно тяжелая оперция.

2024-03-04 10:24 UTC, activeprofi commented on maps/maps.py
> +        filtered_movies = filter(lambda m: len(m["country"].split(",")) >= 2, list_of_movies)
Привет, спасибо за ревью.

А что, если использовать ```.count(",") + 1``` ?
Добавил в [a25a35f](https://github.com/activeprofi/eu-python-learn-challenge/pull/2/commits/a25a35f45341660b3e88721bd5f830042f1f5ed2)

2024-03-11 05:46 UTC, aleksandr-semenov-dbp approved these changes

2024-03-11 08:24 UTC, merged