Add solutions for filter-map problems
activeprofi/eu-python-learn-challenge pull request #3
Opened 2024-02-29 22:38 UTC by activeprofi

2024-03-04 05:27 UTC, aleksandr-semenov-dbp requested changes

2024-03-04 05:27 UTC, aleksandr-semenov-dbp commented on filter_map/filter_map.py
> +        filter_result = [v for b, v in map_result if b is True]
плохой нейминг переменных - `v`, `b`, 
`if b is True` -> `if b`

2024-03-04 10:36 UTC, activeprofi commented on filter_map/filter_map.py
> +        filter_result = [v for b, v in map_result if b is True]
Зарефакторил здесь [2f03bbf](https://github.com/activeprofi/eu-python-learn-challenge/pull/3/commits/2f03bbffe7bf6da42c239801616524e6ab7a538e)

2024-03-11 05:49 UTC, aleksandr-semenov-dbp approved these changes

2024-03-11 05:49 UTC, aleksandr-semenov-dbp commented on filter_map/filter_map.py
> +        filter_result = [func_res for boolean, func_res in map_result if boolean]
называть переменные их типом тоже нежелательно, я бы предложил например `boolean` -> `flag`

2024-03-11 08:23 UTC, merged